version: '3.8'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    platform: linux/arm64/v8
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - citibike-network

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - citibike-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: citibike_user
      POSTGRES_PASSWORD: citibike_pass
      POSTGRES_DB: citibike_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - citibike-network

  spark:
    image: custom-spark:3.5.3-kafka # bitnami/spark:latest
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    volumes:
      - ./spark_jobs:/opt/spark/jobs
    networks:
      - citibike-network

volumes:
  postgres_data:

networks:
  citibike-network:
    driver: bridge