version: '3.8'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    platform: linux/arm64/v8
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - citibike-network

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - citibike-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: citibike_user
      POSTGRES_PASSWORD: citibike_pass
      POSTGRES_DB: citibike_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - citibike-network

  spark:
    image: bitnami/spark:latest
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    volumes:
      - ./spark_jobs:/opt/spark/jobs
      - ./python_app/jars:/opt/spark/jars
    networks:
      - citibike-network

  python_app:
    build: ./python_app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=citibike_user
      - POSTGRES_PASSWORD=citibike_pass
      - POSTGRES_DB=citibike_db
      - STATION_STATUS_URL=https://gbfs.citibikenyc.com/gbfs/en/station_status.json
      - KAFKA_TOPIC=station_status
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - citibike-network

volumes:
  postgres_data:

networks:
  citibike-network:
    driver: bridge